[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
runner = "bootimage runner"
rustflags = ["-C", "link-arg=--image-base=0x800000", "-C", "link-arg=-zmax-page-size=0x1000", "-C", "link-arg=-no-pie"]
